# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vehicle_view.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VehicleView(object):
    def setupUi(self, VehicleView):
        VehicleView.setObjectName("VehicleView")
        VehicleView.resize(1176, 824)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(VehicleView)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabVehicleView = QtWidgets.QTabWidget(VehicleView)
        self.tabVehicleView.setObjectName("tabVehicleView")
        self.tabOverview = QtWidgets.QWidget()
        self.tabOverview.setObjectName("tabOverview")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabOverview)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox = QtWidgets.QGroupBox(self.tabOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_5 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(130, 0))
        self.label.setObjectName("label")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.carName = QtWidgets.QLabel(self.groupBox)
        self.carName.setProperty("jsonAttribute", "display_name")
        self.carName.setProperty("valueAdapter", "qt_json_attribute")
        self.carName.setObjectName("carName")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carName)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.carModel = QtWidgets.QLabel(self.groupBox)
        self.carModel.setProperty("jsonAttribute", "vehicle_config.car_type")
        self.carModel.setProperty("valueAdapter", "qt_json_attribute")
        self.carModel.setObjectName("carModel")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carModel)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setMinimumSize(QtCore.QSize(130, 0))
        self.label_3.setObjectName("label_3")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.carVin = QtWidgets.QLabel(self.groupBox)
        self.carVin.setProperty("jsonAttribute", "vin")
        self.carVin.setProperty("valueAdapter", "qt_json_attribute")
        self.carVin.setObjectName("carVin")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carVin)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(130, 0))
        self.label_4.setObjectName("label_4")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.carSwVersion = QtWidgets.QLabel(self.groupBox)
        self.carSwVersion.setProperty("jsonAttribute", "vehicle_state.car_version")
        self.carSwVersion.setProperty("valueAdapter", "qt_json_attribute")
        self.carSwVersion.setObjectName("carSwVersion")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carSwVersion)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setMinimumSize(QtCore.QSize(130, 0))
        self.label_20.setObjectName("label_20")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.carOdometer = QtWidgets.QLabel(self.groupBox)
        self.carOdometer.setProperty("jsonAttribute", "vehicle_state.odometer")
        self.carOdometer.setProperty("valueAdapter", "qt_json_attribute")
        self.carOdometer.setProperty("units", "distance_units")
        self.carOdometer.setProperty("conversion", "distance_conversion")
        self.carOdometer.setProperty("round", 2)
        self.carOdometer.setObjectName("carOdometer")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.carOdometer)
        self.verticalLayout_9.addWidget(self.groupBox)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tabOverview)
        self.groupBox_6.setObjectName("groupBox_6")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_6)
        self.label_5.setMinimumSize(QtCore.QSize(130, 0))
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.carColor = QtWidgets.QLabel(self.groupBox_6)
        self.carColor.setProperty("jsonAttribute", "vehicle_config.exterior_color")
        self.carColor.setProperty("valueAdapter", "qt_json_attribute")
        self.carColor.setObjectName("carColor")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carColor)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setMinimumSize(QtCore.QSize(130, 0))
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.carWheels = QtWidgets.QLabel(self.groupBox_6)
        self.carWheels.setProperty("jsonAttribute", "vehicle_config.wheel_type")
        self.carWheels.setProperty("valueAdapter", "qt_json_attribute")
        self.carWheels.setObjectName("carWheels")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.carWheels)
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setMinimumSize(QtCore.QSize(130, 0))
        self.label_21.setObjectName("label_21")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.carChargePort = QtWidgets.QLabel(self.groupBox_6)
        self.carChargePort.setProperty("jsonAttribute", "vehicle_config.charge_port_type")
        self.carChargePort.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargePort.setObjectName("carChargePort")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.carChargePort)
        self.label_27 = QtWidgets.QLabel(self.groupBox_6)
        self.label_27.setMinimumSize(QtCore.QSize(130, 0))
        self.label_27.setObjectName("label_27")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_27)
        self.carRHD = QtWidgets.QLabel(self.groupBox_6)
        self.carRHD.setProperty("jsonAttribute", "vehicle_config.rhd")
        self.carRHD.setProperty("valueAdapter", "qt_json_attribute")
        self.carRHD.setObjectName("carRHD")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.carRHD)
        self.label_28 = QtWidgets.QLabel(self.groupBox_6)
        self.label_28.setMinimumSize(QtCore.QSize(130, 0))
        self.label_28.setObjectName("label_28")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_28)
        self.carEUSpec = QtWidgets.QLabel(self.groupBox_6)
        self.carEUSpec.setProperty("jsonAttribute", "vehicle_config.eu_vehicle")
        self.carEUSpec.setProperty("valueAdapter", "qt_json_attribute")
        self.carEUSpec.setObjectName("carEUSpec")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.carEUSpec)
        self.label_29 = QtWidgets.QLabel(self.groupBox_6)
        self.label_29.setMinimumSize(QtCore.QSize(130, 0))
        self.label_29.setObjectName("label_29")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_29)
        self.carAirSuspension = QtWidgets.QLabel(self.groupBox_6)
        self.carAirSuspension.setProperty("jsonAttribute", "vehicle_config.has_air_suspension")
        self.carAirSuspension.setProperty("valueAdapter", "qt_json_attribute")
        self.carAirSuspension.setObjectName("carAirSuspension")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.carAirSuspension)
        self.label_31 = QtWidgets.QLabel(self.groupBox_6)
        self.label_31.setMinimumSize(QtCore.QSize(130, 0))
        self.label_31.setObjectName("label_31")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_31)
        self.carLudicrous = QtWidgets.QLabel(self.groupBox_6)
        self.carLudicrous.setProperty("jsonAttribute", "vehicle_config.has_ludicrous_mode")
        self.carLudicrous.setProperty("valueAdapter", "qt_json_attribute")
        self.carLudicrous.setObjectName("carLudicrous")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.carLudicrous)
        self.label_30 = QtWidgets.QLabel(self.groupBox_6)
        self.label_30.setMinimumSize(QtCore.QSize(130, 0))
        self.label_30.setObjectName("label_30")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.carRoof = QtWidgets.QLabel(self.groupBox_6)
        self.carRoof.setProperty("jsonAttribute", "vehicle_config.roof_color")
        self.carRoof.setProperty("valueAdapter", "qt_json_attribute")
        self.carRoof.setObjectName("carRoof")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carRoof)
        self.label_32 = QtWidgets.QLabel(self.groupBox_6)
        self.label_32.setMinimumSize(QtCore.QSize(130, 0))
        self.label_32.setObjectName("label_32")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_32)
        self.carSpoiler = QtWidgets.QLabel(self.groupBox_6)
        self.carSpoiler.setProperty("jsonAttribute", "vehicle_config.spoiler_type")
        self.carSpoiler.setProperty("valueAdapter", "qt_json_attribute")
        self.carSpoiler.setObjectName("carSpoiler")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carSpoiler)
        self.label_33 = QtWidgets.QLabel(self.groupBox_6)
        self.label_33.setMinimumSize(QtCore.QSize(130, 0))
        self.label_33.setObjectName("label_33")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_33)
        self.carSunRoof = QtWidgets.QLabel(self.groupBox_6)
        self.carSunRoof.setProperty("jsonAttribute", "vehicle_config.sun_roof_installed")
        self.carSunRoof.setProperty("valueAdapter", "qt_json_attribute")
        self.carSunRoof.setObjectName("carSunRoof")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.carSunRoof)
        self.label_35 = QtWidgets.QLabel(self.groupBox_6)
        self.label_35.setMinimumSize(QtCore.QSize(130, 0))
        self.label_35.setObjectName("label_35")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_35)
        self.carSentryAvailable = QtWidgets.QLabel(self.groupBox_6)
        self.carSentryAvailable.setProperty("jsonAttribute", "vehicle_state.sentry_mode_available")
        self.carSentryAvailable.setProperty("valueAdapter", "qt_json_attribute")
        self.carSentryAvailable.setObjectName("carSentryAvailable")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.carSentryAvailable)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tabOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_6 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setMinimumSize(QtCore.QSize(130, 0))
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.carStatus = QtWidgets.QLabel(self.groupBox_2)
        self.carStatus.setProperty("jsonAttribute", "state")
        self.carStatus.setProperty("valueAdapter", "qt_json_attribute")
        self.carStatus.setObjectName("carStatus")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carStatus)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setMinimumSize(QtCore.QSize(130, 0))
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.carDoorsLocked = QtWidgets.QLabel(self.groupBox_2)
        self.carDoorsLocked.setProperty("jsonAttribute", "vehicle_state.locked")
        self.carDoorsLocked.setProperty("valueAdapter", "qt_json_attribute")
        self.carDoorsLocked.setObjectName("carDoorsLocked")
        self.formLayout_6.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carDoorsLocked)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setMinimumSize(QtCore.QSize(130, 0))
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.carSpeed = QtWidgets.QLabel(self.groupBox_2)
        self.carSpeed.setProperty("jsonAttribute", "drive_state.speed")
        self.carSpeed.setProperty("valueAdapter", "qt_json_attribute")
        self.carSpeed.setProperty("units", "speed_units")
        self.carSpeed.setProperty("conversion", "distance_conversion")
        self.carSpeed.setProperty("round", 2)
        self.carSpeed.setObjectName("carSpeed")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carSpeed)
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setMinimumSize(QtCore.QSize(130, 0))
        self.label_34.setObjectName("label_34")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_34)
        self.carSentryEnabled = QtWidgets.QLabel(self.groupBox_2)
        self.carSentryEnabled.setProperty("jsonAttribute", "vehicle_state.sentry_mode")
        self.carSentryEnabled.setProperty("valueAdapter", "qt_json_attribute")
        self.carSentryEnabled.setObjectName("carSentryEnabled")
        self.formLayout_6.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.carSentryEnabled)
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setObjectName("label_36")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_36)
        self.carUserPresent = QtWidgets.QLabel(self.groupBox_2)
        self.carUserPresent.setProperty("jsonAttribute", "vehicle_state.is_user_present")
        self.carUserPresent.setProperty("valueAdapter", "qt_json_attribute")
        self.carUserPresent.setObjectName("carUserPresent")
        self.formLayout_6.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.carUserPresent)
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setObjectName("label_37")
        self.formLayout_6.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_37)
        self.carSpeedLimitActive = QtWidgets.QLabel(self.groupBox_2)
        self.carSpeedLimitActive.setProperty("jsonAttribute", "vehicle_state.speed_limit_mode.active")
        self.carSpeedLimitActive.setProperty("valueAdapter", "qt_json_attribute")
        self.carSpeedLimitActive.setObjectName("carSpeedLimitActive")
        self.formLayout_6.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.carSpeedLimitActive)
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setObjectName("label_38")
        self.formLayout_6.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_38)
        self.carSpeedLimit = QtWidgets.QLabel(self.groupBox_2)
        self.carSpeedLimit.setProperty("jsonAttribute", "vehicle_state.speed_limit_mode.current_limit_mph")
        self.carSpeedLimit.setProperty("valueAdapter", "qt_json_attribute")
        self.carSpeedLimit.setProperty("units", "speed_units")
        self.carSpeedLimit.setProperty("conversion", "distance_conversion")
        self.carSpeedLimit.setProperty("round", 2)
        self.carSpeedLimit.setObjectName("carSpeedLimit")
        self.formLayout_6.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.carSpeedLimit)
        self.carValetMode = QtWidgets.QLabel(self.groupBox_2)
        self.carValetMode.setProperty("jsonAttribute", "vehicle_state.valet_mode")
        self.carValetMode.setProperty("valueAdapter", "qt_json_attribute")
        self.carValetMode.setObjectName("carValetMode")
        self.formLayout_6.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.carValetMode)
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setObjectName("label_40")
        self.formLayout_6.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_40)
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setObjectName("label_41")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_41)
        self.carChargePortOpen = QtWidgets.QLabel(self.groupBox_2)
        self.carChargePortOpen.setProperty("jsonAttribute", "charge_state.charge_port_door_open")
        self.carChargePortOpen.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargePortOpen.setObjectName("carChargePortOpen")
        self.formLayout_6.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.carChargePortOpen)
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setObjectName("label_42")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_42)
        self.carChargePortLatch = QtWidgets.QLabel(self.groupBox_2)
        self.carChargePortLatch.setProperty("jsonAttribute", "charge_state.charge_port_latch")
        self.carChargePortLatch.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargePortLatch.setObjectName("carChargePortLatch")
        self.formLayout_6.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.carChargePortLatch)
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setObjectName("label_39")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_39)
        self.carChargePortWinter = QtWidgets.QLabel(self.groupBox_2)
        self.carChargePortWinter.setProperty("jsonAttribute", "charge_state.charge_port_cold_weather_mode")
        self.carChargePortWinter.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargePortWinter.setObjectName("carChargePortWinter")
        self.formLayout_6.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.carChargePortWinter)
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setObjectName("label_43")
        self.formLayout_6.setWidget(14, QtWidgets.QFormLayout.LabelRole, self.label_43)
        self.carInService = QtWidgets.QLabel(self.groupBox_2)
        self.carInService.setProperty("jsonAttribute", "in_service")
        self.carInService.setProperty("valueAdapter", "qt_json_attribute")
        self.carInService.setObjectName("carInService")
        self.formLayout_6.setWidget(14, QtWidgets.QFormLayout.FieldRole, self.carInService)
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setObjectName("label_48")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_48)
        self.carShift = QtWidgets.QLabel(self.groupBox_2)
        self.carShift.setProperty("jsonAttribute", "drive_state.shift_state")
        self.carShift.setProperty("valueAdapter", "qt_json_attribute")
        self.carShift.setObjectName("carShift")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carShift)
        self.label_49 = QtWidgets.QLabel(self.groupBox_2)
        self.label_49.setObjectName("label_49")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_49)
        self.carPower = QtWidgets.QLabel(self.groupBox_2)
        self.carPower.setProperty("jsonAttribute", "drive_state.power")
        self.carPower.setProperty("valueAdapter", "engine_power")
        self.carPower.setObjectName("carPower")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.carPower)
        self.verticalLayout_15.addWidget(self.groupBox_2)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tabOverview)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.formLayout_20 = QtWidgets.QFormLayout()
        self.formLayout_20.setObjectName("formLayout_20")
        self.label_55 = QtWidgets.QLabel(self.groupBox_7)
        self.label_55.setMinimumSize(QtCore.QSize(130, 0))
        self.label_55.setObjectName("label_55")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_55)
        self.carHeading = QtWidgets.QLabel(self.groupBox_7)
        self.carHeading.setProperty("valueAdapter", "qt_json_attribute")
        self.carHeading.setObjectName("carHeading")
        self.formLayout_20.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carHeading)
        self.label_51 = QtWidgets.QLabel(self.groupBox_7)
        self.label_51.setObjectName("label_51")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_51)
        self.carLatitude = QtWidgets.QLabel(self.groupBox_7)
        self.carLatitude.setProperty("jsonAttribute", "drive_state.latitude")
        self.carLatitude.setObjectName("carLatitude")
        self.formLayout_20.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carLatitude)
        self.label_53 = QtWidgets.QLabel(self.groupBox_7)
        self.label_53.setObjectName("label_53")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_53)
        self.carLongitude = QtWidgets.QLabel(self.groupBox_7)
        self.carLongitude.setProperty("jsonAttribute", "drive_state.longitude")
        self.carLongitude.setProperty("valueAdapter", "qt_json_attribute")
        self.carLongitude.setObjectName("carLongitude")
        self.formLayout_20.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carLongitude)
        self.verticalLayout_13.addLayout(self.formLayout_20)
        self.linkToLocation = QtWidgets.QLabel(self.groupBox_7)
        self.linkToLocation.setOpenExternalLinks(True)
        self.linkToLocation.setProperty("valueAdapter", "qt_location_link")
        self.linkToLocation.setObjectName("linkToLocation")
        self.verticalLayout_13.addWidget(self.linkToLocation)
        self.verticalLayout_15.addWidget(self.groupBox_7)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tabOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_8.setObjectName("formLayout_8")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setMinimumSize(QtCore.QSize(130, 0))
        self.label_10.setObjectName("label_10")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.carChargeLevel = QtWidgets.QProgressBar(self.groupBox_5)
        self.carChargeLevel.setMaximumSize(QtCore.QSize(150, 20))
        self.carChargeLevel.setProperty("value", 50)
        self.carChargeLevel.setTextVisible(True)
        self.carChargeLevel.setProperty("jsonAttribute", "charge_state.battery_level")
        self.carChargeLevel.setProperty("valueAdapter", "qt_progress_bar")
        self.carChargeLevel.setProperty("targetProperty", "value")
        self.carChargeLevel.setObjectName("carChargeLevel")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carChargeLevel)
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setMinimumSize(QtCore.QSize(130, 0))
        self.label_11.setObjectName("label_11")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.carRange = QtWidgets.QLabel(self.groupBox_5)
        self.carRange.setProperty("jsonAttribute", "charge_state.battery_range")
        self.carRange.setProperty("valueAdapter", "qt_json_attribute")
        self.carRange.setProperty("units", "distance_units")
        self.carRange.setProperty("conversion", "distance_conversion")
        self.carRange.setProperty("round", 2)
        self.carRange.setObjectName("carRange")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carRange)
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setMinimumSize(QtCore.QSize(130, 0))
        self.label_22.setObjectName("label_22")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.carMaxRange = QtWidgets.QLabel(self.groupBox_5)
        self.carMaxRange.setProperty("valueAdapter", "qt_max_range")
        self.carMaxRange.setProperty("units", "distance_units")
        self.carMaxRange.setProperty("conversion", "distance_conversion")
        self.carMaxRange.setProperty("round", 2)
        self.carMaxRange.setObjectName("carMaxRange")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carMaxRange)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setMinimumSize(QtCore.QSize(130, 0))
        self.label_12.setObjectName("label_12")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.carChargeLimit = QtWidgets.QLabel(self.groupBox_5)
        self.carChargeLimit.setProperty("jsonAttribute", "charge_state.charge_limit_soc")
        self.carChargeLimit.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargeLimit.setProperty("units", "%")
        self.carChargeLimit.setObjectName("carChargeLimit")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.carChargeLimit)
        self.label_26 = QtWidgets.QLabel(self.groupBox_5)
        self.label_26.setMinimumSize(QtCore.QSize(130, 0))
        self.label_26.setObjectName("label_26")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.carChargeVoltage = QtWidgets.QLabel(self.groupBox_5)
        self.carChargeVoltage.setProperty("valueAdapter", "charge_tension")
        self.carChargeVoltage.setProperty("units", "V")
        self.carChargeVoltage.setObjectName("carChargeVoltage")
        self.formLayout_8.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.carChargeVoltage)
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setMinimumSize(QtCore.QSize(130, 0))
        self.label_14.setObjectName("label_14")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.carChargePowerEffective = QtWidgets.QLabel(self.groupBox_5)
        self.carChargePowerEffective.setProperty("valueAdapter", "charge_power")
        self.carChargePowerEffective.setProperty("units", "kW")
        self.carChargePowerEffective.setObjectName("carChargePowerEffective")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.carChargePowerEffective)
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setMinimumSize(QtCore.QSize(130, 0))
        self.label_13.setObjectName("label_13")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.carChargingState = QtWidgets.QLabel(self.groupBox_5)
        self.carChargingState.setProperty("jsonAttribute", "charge_state.charging_state")
        self.carChargingState.setProperty("valueAdapter", "qt_json_attribute")
        self.carChargingState.setObjectName("carChargingState")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carChargingState)
        self.label_18 = QtWidgets.QLabel(self.groupBox_5)
        self.label_18.setMinimumSize(QtCore.QSize(130, 0))
        self.label_18.setObjectName("label_18")
        self.formLayout_8.setWidget(15, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.carChargeAdded = QtWidgets.QLabel(self.groupBox_5)
        self.carChargeAdded.setProperty("valueAdapter", "charge_added")
        self.carChargeAdded.setProperty("units", "kWh")
        self.carChargeAdded.setObjectName("carChargeAdded")
        self.formLayout_8.setWidget(15, QtWidgets.QFormLayout.FieldRole, self.carChargeAdded)
        self.label_46 = QtWidgets.QLabel(self.groupBox_5)
        self.label_46.setObjectName("label_46")
        self.formLayout_8.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_46)
        self.carChargeCurrentEffective = QtWidgets.QLabel(self.groupBox_5)
        self.carChargeCurrentEffective.setProperty("valueAdapter", "charge_current")
        self.carChargeCurrentEffective.setProperty("units", "A")
        self.carChargeCurrentEffective.setObjectName("carChargeCurrentEffective")
        self.formLayout_8.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.carChargeCurrentEffective)
        self.label_45 = QtWidgets.QLabel(self.groupBox_5)
        self.label_45.setObjectName("label_45")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_45)
        self.carChargeTimeLeft = QtWidgets.QLabel(self.groupBox_5)
        self.carChargeTimeLeft.setProperty("valueAdapter", "charge_time_left")
        self.carChargeTimeLeft.setProperty("conversion", "to_string")
        self.carChargeTimeLeft.setObjectName("carChargeTimeLeft")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.carChargeTimeLeft)
        self.verticalLayout_10.addWidget(self.groupBox_5)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tabOverview)
        self.groupBox_8.setObjectName("groupBox_8")
        self.formLayout_17 = QtWidgets.QFormLayout(self.groupBox_8)
        self.formLayout_17.setObjectName("formLayout_17")
        self.label_44 = QtWidgets.QLabel(self.groupBox_8)
        self.label_44.setObjectName("label_44")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_44)
        self.carChargePowerDrawn = QtWidgets.QLabel(self.groupBox_8)
        self.carChargePowerDrawn.setProperty("valueAdapter", "charge_power_drawn")
        self.carChargePowerDrawn.setProperty("units", "kW")
        self.carChargePowerDrawn.setProperty("round", 2)
        self.carChargePowerDrawn.setObjectName("carChargePowerDrawn")
        self.formLayout_17.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carChargePowerDrawn)
        self.label_47 = QtWidgets.QLabel(self.groupBox_8)
        self.label_47.setObjectName("label_47")
        self.formLayout_17.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_47)
        self.carChargeEfficiency = QtWidgets.QLabel(self.groupBox_8)
        self.carChargeEfficiency.setProperty("valueAdapter", "charge_efficiency")
        self.carChargeEfficiency.setProperty("units", "%")
        self.carChargeEfficiency.setProperty("round", 2)
        self.carChargeEfficiency.setObjectName("carChargeEfficiency")
        self.formLayout_17.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.carChargeEfficiency)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setMinimumSize(QtCore.QSize(130, 0))
        self.label_23.setObjectName("label_23")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.carChargeCurrentDrawn = QtWidgets.QLabel(self.groupBox_8)
        self.carChargeCurrentDrawn.setProperty("jsonAttribute", "charge_state.charger_actual_current")
        self.carChargeCurrentDrawn.setProperty("valueAdapter", "qt_current")
        self.carChargeCurrentDrawn.setProperty("units", "A")
        self.carChargeCurrentDrawn.setObjectName("carChargeCurrentDrawn")
        self.formLayout_17.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carChargeCurrentDrawn)
        self.label_25 = QtWidgets.QLabel(self.groupBox_8)
        self.label_25.setMinimumSize(QtCore.QSize(130, 0))
        self.label_25.setObjectName("label_25")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.carChargeCurrentMax = QtWidgets.QLabel(self.groupBox_8)
        self.carChargeCurrentMax.setProperty("jsonAttribute", "charge_state.charge_current_request_max")
        self.carChargeCurrentMax.setProperty("valueAdapter", "qt_current")
        self.carChargeCurrentMax.setProperty("units", "A")
        self.carChargeCurrentMax.setObjectName("carChargeCurrentMax")
        self.formLayout_17.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.carChargeCurrentMax)
        self.label_24 = QtWidgets.QLabel(self.groupBox_8)
        self.label_24.setMinimumSize(QtCore.QSize(130, 0))
        self.label_24.setObjectName("label_24")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.carChargePhases = QtWidgets.QLabel(self.groupBox_8)
        self.carChargePhases.setProperty("valueAdapter", "charge_phases")
        self.carChargePhases.setObjectName("carChargePhases")
        self.formLayout_17.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carChargePhases)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tabOverview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_7 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_7.setObjectName("formLayout_7")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setMinimumSize(QtCore.QSize(130, 0))
        self.label_15.setObjectName("label_15")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.carCabinTemp = QtWidgets.QLabel(self.groupBox_4)
        self.carCabinTemp.setProperty("valueAdapter", "qt_json_attribute")
        self.carCabinTemp.setProperty("units", "temperature_units")
        self.carCabinTemp.setObjectName("carCabinTemp")
        self.formLayout_7.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.carCabinTemp)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setMinimumSize(QtCore.QSize(130, 0))
        self.label_16.setObjectName("label_16")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.carOutsideTemp = QtWidgets.QLabel(self.groupBox_4)
        self.carOutsideTemp.setProperty("jsonAttribute", "climate_state.outside_temp")
        self.carOutsideTemp.setProperty("valueAdapter", "qt_json_attribute")
        self.carOutsideTemp.setProperty("units", "temperature_units")
        self.carOutsideTemp.setObjectName("carOutsideTemp")
        self.formLayout_7.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.carOutsideTemp)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setMinimumSize(QtCore.QSize(130, 0))
        self.label_17.setObjectName("label_17")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.carClimateEnabled = QtWidgets.QLabel(self.groupBox_4)
        self.carClimateEnabled.setProperty("jsonAttribute", "climate_state.is_climate_on")
        self.carClimateEnabled.setProperty("valueAdapter", "qt_json_attribute")
        self.carClimateEnabled.setObjectName("carClimateEnabled")
        self.formLayout_7.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.carClimateEnabled)
        self.verticalLayout_10.addWidget(self.groupBox_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem2)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tabOverview)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.action_wake_up = QtWidgets.QPushButton(self.groupBox_3)
        self.action_wake_up.setObjectName("action_wake_up")
        self.horizontalLayout_2.addWidget(self.action_wake_up)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.groupBox_3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_6.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.action_honk = QtWidgets.QPushButton(self.groupBox_3)
        self.action_honk.setObjectName("action_honk")
        self.horizontalLayout_3.addWidget(self.action_honk)
        self.action_flash = QtWidgets.QPushButton(self.groupBox_3)
        self.action_flash.setObjectName("action_flash")
        self.horizontalLayout_3.addWidget(self.action_flash)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_11.addWidget(self.groupBox_3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.tabVehicleView.addTab(self.tabOverview, "")
        self.tabOptionCodes = QtWidgets.QWidget()
        self.tabOptionCodes.setObjectName("tabOptionCodes")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabOptionCodes)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_19 = QtWidgets.QLabel(self.tabOptionCodes)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.tableView = QtWidgets.QTableView(self.tabOptionCodes)
        self.tableView.setSortingEnabled(False)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setVisible(False)
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.tableView.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableView)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.tabVehicleView.addTab(self.tabOptionCodes, "")
        self.tabRawData = QtWidgets.QWidget()
        self.tabRawData.setObjectName("tabRawData")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tabRawData)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameKeyValue = QtWidgets.QTableView(self.tabRawData)
        self.frameKeyValue.setObjectName("frameKeyValue")
        self.frameKeyValue.horizontalHeader().setVisible(False)
        self.frameKeyValue.horizontalHeader().setHighlightSections(True)
        self.frameKeyValue.horizontalHeader().setStretchLastSection(True)
        self.frameKeyValue.verticalHeader().setVisible(False)
        self.horizontalLayout.addWidget(self.frameKeyValue)
        self.frameJson = QtWidgets.QPlainTextEdit(self.tabRawData)
        self.frameJson.setReadOnly(True)
        self.frameJson.setObjectName("frameJson")
        self.horizontalLayout.addWidget(self.frameJson)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.tabVehicleView.addTab(self.tabRawData, "")
        self.verticalLayout.addWidget(self.tabVehicleView)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(VehicleView)
        self.tabVehicleView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(VehicleView)

    def retranslateUi(self, VehicleView):
        _translate = QtCore.QCoreApplication.translate
        VehicleView.setWindowTitle(_translate("VehicleView", "Account Credentials"))
        self.groupBox.setTitle(_translate("VehicleView", "Basic Details"))
        self.label.setText(_translate("VehicleView", "Name:"))
        self.carName.setText(_translate("VehicleView", "carName"))
        self.label_2.setText(_translate("VehicleView", "Model:"))
        self.carModel.setText(_translate("VehicleView", "carModel"))
        self.label_3.setText(_translate("VehicleView", "VIN:"))
        self.carVin.setText(_translate("VehicleView", "carVin"))
        self.label_4.setText(_translate("VehicleView", "SW Version:"))
        self.carSwVersion.setText(_translate("VehicleView", "carSwVersion"))
        self.label_20.setText(_translate("VehicleView", "Odometer:"))
        self.carOdometer.setText(_translate("VehicleView", "carOdometer"))
        self.groupBox_6.setTitle(_translate("VehicleView", "Car Configuration"))
        self.label_5.setText(_translate("VehicleView", "Color:"))
        self.carColor.setText(_translate("VehicleView", "carColor"))
        self.label_6.setText(_translate("VehicleView", "Wheel Type:"))
        self.carWheels.setText(_translate("VehicleView", "carWheels"))
        self.label_21.setText(_translate("VehicleView", "Charge Port:"))
        self.carChargePort.setText(_translate("VehicleView", "carChargePort"))
        self.label_27.setText(_translate("VehicleView", "RHD:"))
        self.carRHD.setText(_translate("VehicleView", "carRHD"))
        self.label_28.setText(_translate("VehicleView", "EU Spec:"))
        self.carEUSpec.setText(_translate("VehicleView", "carEUSpec"))
        self.label_29.setText(_translate("VehicleView", "Air Suspension:"))
        self.carAirSuspension.setText(_translate("VehicleView", "carAirSuspension"))
        self.label_31.setText(_translate("VehicleView", "Ludicrous:"))
        self.carLudicrous.setText(_translate("VehicleView", "carLudicrous"))
        self.label_30.setText(_translate("VehicleView", "Roof:"))
        self.carRoof.setText(_translate("VehicleView", "carRoof"))
        self.label_32.setText(_translate("VehicleView", "Spoiler:"))
        self.carSpoiler.setText(_translate("VehicleView", "carSpoiler"))
        self.label_33.setText(_translate("VehicleView", "Sun Roof:"))
        self.carSunRoof.setText(_translate("VehicleView", "carSunRoof"))
        self.label_35.setText(_translate("VehicleView", "Sentry Available:"))
        self.carSentryAvailable.setText(_translate("VehicleView", "carSentryAvailable"))
        self.groupBox_2.setTitle(_translate("VehicleView", "Car State"))
        self.label_7.setText(_translate("VehicleView", "Car State:"))
        self.carStatus.setText(_translate("VehicleView", "carStatus"))
        self.label_8.setText(_translate("VehicleView", "Doors Locked:"))
        self.carDoorsLocked.setText(_translate("VehicleView", "carDoorsLocked"))
        self.label_9.setText(_translate("VehicleView", "Car Speed:"))
        self.carSpeed.setText(_translate("VehicleView", "carSpeed"))
        self.label_34.setText(_translate("VehicleView", "Sentry Enabled:"))
        self.carSentryEnabled.setText(_translate("VehicleView", "carSentryEnabled"))
        self.label_36.setText(_translate("VehicleView", "User Present:"))
        self.carUserPresent.setText(_translate("VehicleView", "carUserPresent"))
        self.label_37.setText(_translate("VehicleView", "Speed Limit Active:"))
        self.carSpeedLimitActive.setText(_translate("VehicleView", "carSpeedLimitActive"))
        self.label_38.setText(_translate("VehicleView", "Speed Limit:"))
        self.carSpeedLimit.setText(_translate("VehicleView", "carSpeedLimit"))
        self.carValetMode.setText(_translate("VehicleView", "carValetMode"))
        self.label_40.setText(_translate("VehicleView", "Valet Mode Enabled:"))
        self.label_41.setText(_translate("VehicleView", "Charge Port Open:"))
        self.carChargePortOpen.setText(_translate("VehicleView", "carChargePortOpen"))
        self.label_42.setText(_translate("VehicleView", "Charge Port Latch:"))
        self.carChargePortLatch.setText(_translate("VehicleView", "carChargePortLatched"))
        self.label_39.setText(_translate("VehicleView", "C.Port Winter Mode:"))
        self.carChargePortWinter.setText(_translate("VehicleView", "carChargePortWinter"))
        self.label_43.setText(_translate("VehicleView", "Car In Service:"))
        self.carInService.setText(_translate("VehicleView", "carInService"))
        self.label_48.setText(_translate("VehicleView", "Shift:"))
        self.carShift.setText(_translate("VehicleView", "carShift"))
        self.label_49.setText(_translate("VehicleView", "Engine Power:"))
        self.carPower.setText(_translate("VehicleView", "carPower"))
        self.groupBox_7.setTitle(_translate("VehicleView", "Car Position"))
        self.label_55.setText(_translate("VehicleView", "Heading:"))
        self.carHeading.setText(_translate("VehicleView", "carHeading"))
        self.carHeading.setProperty("jsonAttribute", _translate("VehicleView", "drive_state.heading"))
        self.label_51.setText(_translate("VehicleView", "Latitude:"))
        self.carLatitude.setText(_translate("VehicleView", "carLatitude"))
        self.carLatitude.setProperty("valueAdapter", _translate("VehicleView", "qt_json_attribute"))
        self.label_53.setText(_translate("VehicleView", "Longitude"))
        self.carLongitude.setText(_translate("VehicleView", "carLongitude"))
        self.linkToLocation.setText(_translate("VehicleView", "linkToLocation"))
        self.groupBox_5.setTitle(_translate("VehicleView", "Charge"))
        self.label_10.setText(_translate("VehicleView", "Current Charge:"))
        self.label_11.setText(_translate("VehicleView", "Current Range:"))
        self.carRange.setText(_translate("VehicleView", "carRange"))
        self.label_22.setText(_translate("VehicleView", "Estimated Max Range:"))
        self.carMaxRange.setText(_translate("VehicleView", "carMaxRange"))
        self.label_12.setText(_translate("VehicleView", "Charge Limit:"))
        self.carChargeLimit.setText(_translate("VehicleView", "carChargeLimit"))
        self.label_26.setText(_translate("VehicleView", "Tension:"))
        self.carChargeVoltage.setText(_translate("VehicleView", "carChargeVoltage"))
        self.label_14.setText(_translate("VehicleView", "Power:"))
        self.carChargePowerEffective.setText(_translate("VehicleView", "carChargePowerEffective"))
        self.label_13.setText(_translate("VehicleView", "Charging State:"))
        self.carChargingState.setText(_translate("VehicleView", "carChargingState"))
        self.label_18.setText(_translate("VehicleView", "Charge Added:"))
        self.carChargeAdded.setText(_translate("VehicleView", "carChargeAdded"))
        self.label_46.setText(_translate("VehicleView", "Current:"))
        self.carChargeCurrentEffective.setText(_translate("VehicleView", "carChargeCurrentEffective"))
        self.label_45.setText(_translate("VehicleView", "Time To Complete:"))
        self.carChargeTimeLeft.setText(_translate("VehicleView", "carChargeTimeLeft"))
        self.groupBox_8.setTitle(_translate("VehicleView", "On Board Charger"))
        self.label_44.setText(_translate("VehicleView", "Power Drawn:"))
        self.carChargePowerDrawn.setText(_translate("VehicleView", "carChargePowerDrawn"))
        self.label_47.setText(_translate("VehicleView", "Charge Efficiency:"))
        self.carChargeEfficiency.setText(_translate("VehicleView", "carChargeEfficiency"))
        self.label_23.setText(_translate("VehicleView", "Current Drawn:"))
        self.carChargeCurrentDrawn.setText(_translate("VehicleView", "carChargeCurrentDrawn"))
        self.label_25.setText(_translate("VehicleView", "Max Current Combined:"))
        self.carChargeCurrentMax.setText(_translate("VehicleView", "carChargeCurrentMax"))
        self.label_24.setText(_translate("VehicleView", "Phases:"))
        self.carChargePhases.setText(_translate("VehicleView", "carChargePhases"))
        self.groupBox_4.setTitle(_translate("VehicleView", "Climate"))
        self.label_15.setText(_translate("VehicleView", "Cabin Temperature:"))
        self.carCabinTemp.setText(_translate("VehicleView", "carCabinTemp"))
        self.carCabinTemp.setProperty("jsonAttribute", _translate("VehicleView", "climate_state.inside_temp"))
        self.label_16.setText(_translate("VehicleView", "Outside Temperature:"))
        self.carOutsideTemp.setText(_translate("VehicleView", "carOutsideTemp"))
        self.label_17.setText(_translate("VehicleView", "Climate Enabled:"))
        self.carClimateEnabled.setText(_translate("VehicleView", "carClimateEnabled"))
        self.groupBox_3.setTitle(_translate("VehicleView", "Car Controls"))
        self.action_wake_up.setText(_translate("VehicleView", "Wake Up Car"))
        self.action_honk.setText(_translate("VehicleView", "Honk"))
        self.action_flash.setText(_translate("VehicleView", "Flash Ligths"))
        self.tabVehicleView.setTabText(self.tabVehicleView.indexOf(self.tabOverview), _translate("VehicleView", "Overview"))
        self.label_19.setText(_translate("VehicleView", "WARNING: The option codes returned by Tesla are all over the place and many times they are not representative of the actual real codes for your car"))
        self.tabVehicleView.setTabText(self.tabVehicleView.indexOf(self.tabOptionCodes), _translate("VehicleView", "Option Codes"))
        self.tabVehicleView.setTabText(self.tabVehicleView.indexOf(self.tabRawData), _translate("VehicleView", "Raw Data"))


